services:
  - type: web
    name: belcorp-shop-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: Belcorp Shop API
      - key: BACKEND_CORS_ORIGINS
        value: '["http://localhost:3000","http://localhost:8000","https://belcorp-shop-web-ed259.web.app"]'
      - key: SECRET_KEY
        value: belcorp-shop-secret-key-2024
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
